### ISSUE TITLE
Error when running with mgcv::gamm

### ISSUE THREAD

**Issue by nick-gauthier** [nspope/corMLPE#1]
This is a great package, thank you for implementing this. However I'm getting an error when I try to use corMLPE when fitting a gamm in mgcv. Running the following commands:

```
library(corMLPE)
dat <- simulate_IBD_corMLPE(elements = 50)
mgcv::gamm(y ~ s(x), correlation = corMLPE(form=~pop1+pop2), data = dat)
```

Results in the error
`Error in matrix(0, size.cg[i], size.cg[i]) : object 'size.cg' not found`

I've tracked this error down to `extract.lme.cov2` command in gamm, but am at a loss as to what to try next. I can confirm that the issue is specifically some interaction between corMLPE and gamm, as corMLPE works for me outside of gamm (gls) and gamm runs successfully with a different correlation structure.

Any help on this issue would be greatly appreciated!

**Comment by nspope** [comment]
Fixed in https://github.com/nspope/corMLPE/commit/2f935046fb9483fc7dd3bb28da089f1446901255.

The underlying issue was that corMatrix.corMLPE would return a sparse matrix class from the Matrix package. This is because with large datasets, it is infeasible to explicitly form the dense correlation matrix. Whereas, the helper functions for mgcv::gamm expect a dense matrix primitive. I've overloaded methods such that mgcv::gamm will now work as expected (e.g. efficiently, using a sparse matrix) when there's no grouping factor associated with the correlation structure.

If there is a grouping factor in the covariance structure, gamm will still work; however it will internally coerce the sparse matrix into a dense matrix. Meaning, massive slow downs/memory issues for models fit to very large datasets. This is a deeper problem that I don't see a clear way to fix without modifying code from mgcv.

Thanks for bringing to my attention, and reopen if you run into related issues.
